# Generated by Django 4.0.2 on 2022-03-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('phone_num', models.CharField(max_length=5000)),
                ('email', models.EmailField(max_length=254)),
                ('tour_id', models.IntegerField()),
            ],
        ),
    ]
