# Generated by Django 4.0.2 on 2022-03-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaz', '0002_tourists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=5000)),
                ('tour_price', models.CharField(max_length=5000)),
                ('tour_inf', models.CharField(max_length=5000)),
                ('time', models.TimeField(max_length=4000)),
                ('tour_id', models.IntegerField()),
            ],
        ),
    ]
