# Generated by Django 4.0.2 on 2022-03-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaz', '0003_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('is_published', models.BooleanField(default=True, verbose_name='Tour')),
            ],
        ),
    ]
