# Generated by Django 4.0.2 on 2022-04-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaz', '0004_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('describe', models.TextField(default='DataFlair Django')),
            ],
        ),
    ]
