# Generated by Django 4.0.2 on 2022-04-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaz', '0006_posts_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourists',
            name='sale_ticket',
            field=models.BooleanField(default='False'),
        ),
    ]
