# Generated by Django 4.0.2 on 2022-04-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaz', '0007_tourists_sale_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourists',
            name='discount',
            field=models.BooleanField(default='False'),
        ),
    ]
