# Generated by Django 4.0.2 on 2022-04-14 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaz', '0008_tourists_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourists',
            name='sale_ticket',
        ),
    ]
