# Generated by Django 4.0.2 on 2022-04-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaz', '0009_remove_tourists_sale_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourists',
            options={'ordering': ['name', 'email'], 'verbose_name': 'Турист', 'verbose_name_plural': 'Туристтер'},
        ),
    ]
