# Generated by Django 4.0.2 on 2022-04-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaz', '0010_alter_tourists_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourists',
            name='city',
            field=models.CharField(choices=[('1', 'Almaty'), ('2', 'Nursultan'), ('3', 'Shymkent'), ('4', 'Aktau'), ('5', 'Other')], default=0, max_length=300),
        ),
        migrations.AddField(
            model_name='tourists',
            name='select_class',
            field=models.CharField(choices=[('1', 'Eco'), ('2', 'Vip'), ('3', 'Lux')], default=0, max_length=300),
        ),
    ]
