# Generated by Django 4.0.2 on 2022-04-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaz', '0011_tourists_city_tourists_select_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('about', models.CharField(max_length=250)),
                ('type_of_class', models.TextField(blank=True)),
                ('chargers', models.BooleanField(default='False')),
                ('special_meal', models.BooleanField(default='False')),
                ('snacks', models.BooleanField(default='False')),
                ('drinks', models.BooleanField(default='False')),
                ('local_wifi', models.BooleanField(default='False')),
                ('blanket', models.BooleanField(default='False')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
