# Generated by Django 4.0.2 on 2022-04-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaz', '0012_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
